SET aad_auth_validate_oids_in_tenant = OFF;
DROP USER IF EXISTS '${WORKLOAD_IDENTITY_NAME}';
CREATE AADUSER '${WORKLOAD_IDENTITY_NAME}' IDENTIFIED BY '${WORKLOAD_IDENTITY_ID}';
GRANT ALL PRIVILEGES ON airsonic.* TO '${WORKLOAD_IDENTITY_NAME}'@'%';
FLUSH privileges;
