apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: airsonic-data
    namespace: ${KUBERNETES_NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 10Gi