apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: airsonic-9c07c78d-07c0-621c-b744-50eccae3acec
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi