apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: airsonic-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 10Gi