apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airsonic
  name: airsonic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airsonic
  template:
    metadata:
      labels:
        app: airsonic
        azure.workload.identity/use: "true"
      name: airsonic-deployment
    spec:
      containers:
      - image: ${ACR_NAME_FULL}/${AIRSONIC_CONTAINER}:${AIRSONIC_VERSION}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: spring.datasource.driver-class-name
            value: com.mysql.cj.jdbc.Driver
          - name: spring.datasource.url
            valueFrom:
              secretKeyRef:
                key: spring.datasource.url
                name: airsonic-secrets
          - name: spring.datasource.username
            valueFrom:
              secretKeyRef:
                key: spring.datasource.username
                name: airsonic-secrets          
        imagePullPolicy: Always
        name: airsonic
        ports:
          - containerPort: 4040
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/airsonic/music
          name: airsonic-data
          subPath: music
        - mountPath: /var/music
          name: airsonic-data
          subPath: music
        - mountPath: /var/airsonic/podcasts
          name: airsonic-data
          subPath: podcasts
        - mountPath: /var/podcasts
          name: airsonic-data
          subPath: podcasts
        - mountPath: /var/airsonic/playlists
          name: airsonic-data
          subPath: playlists
      restartPolicy: Always

      serviceAccountName: workload-identity-sa

      volumes:
      - name: airsonic-data
        persistentVolumeClaim:
          claimName: airsonic-data