apiVersion: v1
kind: Service
metadata:
  name: airsonic-svc
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  ports:
  - name: port4040
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    app: airsonic
  sessionAffinity: None
  type: LoadBalancer