apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: $WORKLOAD_IDENTITY_ID
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa